"use client";

import { useId } from "react";
import Link from "next/link";
import { BRAND_ORANGE_STOPS, BRAND_WHITE_STOPS, LOGO_GEOMETRY as G } from "@shop/shared";
import { useI18n } from "@/i18n/context";

/**
 * ChiSetup logo (DESIGN-V3 §6) — the same vector geometry as the Mini App
 * (`frontend/components/Logo.tsx`), from `@shop/shared` (generated by
 * docs/brand/v3/tools/gen_brand.py). Hand-built chamfered, slanted letterforms: «Ch» white, the
 * «i» split diagonally (white stem, orange dot), «Setup» in the orange gradient.
 *
 * `Wordmark` is the bare wordmark (header, footer, sheets); `LogoFull` adds the HUD brackets and
 * the «GAMING GEAR & SETUP» line (login). The tagline is the brand's own English line, part of
 * the artwork, so it is not translated. Paths, not text: crisp at 18–28px and font-independent.
 */

function Stops({ stops }: { stops: typeof BRAND_WHITE_STOPS }) {
  return (
    <>
      {stops.map(([o, c]) => (
        <stop key={o} offset={o} stopColor={c} />
      ))}
    </>
  );
}

function LogoSvg({ full, width, height, className = "" }: { full: boolean; width: number; height: number; className?: string }) {
  const id = useId().replace(/:/g, "");
  return (
    <svg
      role="img"
      aria-label={full ? "ChiSetup — Gaming Gear & Setup" : "ChiSetup"}
      viewBox={full ? G.fullViewBox : G.compactViewBox}
      width={width}
      height={height}
      className={`block shrink-0 select-none ${className}`}
    >
      <defs>
        <linearGradient id={`${id}w`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.whiteGradient.y1} y2={G.whiteGradient.y2}>
          <Stops stops={BRAND_WHITE_STOPS} />
        </linearGradient>
        <linearGradient id={`${id}o`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.orangeGradient.y1} y2={G.orangeGradient.y2}>
          <Stops stops={BRAND_ORANGE_STOPS} />
        </linearGradient>
      </defs>
      <path fill={`url(#${id}w)`} d={G.white} />
      <path fill={`url(#${id}o)`} fillRule="evenodd" d={G.orange} />
      {full && (
        <>
          <path fill={G.taglineColor} d={G.tagline} />
          <path fill="#FFFFFF" d={G.bracketsWhite} />
          <path fill="#FF6600" d={G.bracketsOrange} />
        </>
      )}
    </svg>
  );
}

/** Bare wordmark; `size` = rendered height in px (cap height ≈ 74% of it). */
export function Wordmark({ size = 22, className = "" }: { size?: number; className?: string }) {
  return <LogoSvg full={false} height={size} width={Math.round(size * G.compactAspect)} className={className} />;
}

/** Wordmark in HUD brackets + tagline; `width` in px. */
export function LogoFull({ width = 280, className = "" }: { width?: number; className?: string }) {
  return <LogoSvg full width={width} height={Math.round(width / G.fullAspect)} className={className} />;
}

export function Logo() {
  const { t, href } = useI18n();
  return (
    <Link
      href={href("/")}
      aria-label={t("header.home")}
      className="group inline-flex shrink-0 items-center rounded-[var(--r)] py-1 transition-[filter] duration-150 hover:[filter:drop-shadow(0_0_10px_rgba(255,102,0,.35))]"
    >
      <Wordmark size={24} />
    </Link>
  );
}
