"use client";

import { useId } from "react";
import { BRAND_ORANGE_STOPS, BRAND_WHITE_STOPS, LOGO_GEOMETRY as G } from "@shop/shared";

/**
 * ChiSetup logo (DESIGN-V3 §6) — the same vector geometry as the website
 * (`site/components/layout/Logo.tsx`), from `@shop/shared` (generated by
 * docs/brand/v3/tools/gen_brand.py). Hand-built chamfered, slanted letterforms: "Ch" white,
 * the "i" split diagonally (white stem, orange dot), "Setup" in the orange gradient.
 *
 *   - `compact` — the wordmark alone, for headers;
 *   - `full`    — wordmark inside HUD brackets with the "GAMING GEAR & SETUP" tagline (sign-off,
 *                 error screen).
 *
 * Paths, not text: renders identically before fonts load and stays crisp at 18–28px.
 * Not a link: in the Mini App the catalog tab is "home".
 * Static SVG/PNG versions for Telegram itself (bot avatar, Mini App cover) live in docs/brand/v3/.
 */

type Size = "sm" | "md" | "lg";
type Variant = "compact" | "full";

/** compact: rendered height in px (cap height ≈ 74% of it). */
const COMPACT_H: Record<Size, number> = { sm: 18, md: 22, lg: 26 };
/** full: rendered width in px. */
const FULL_W: Record<Size, number> = { sm: 220, md: 268, lg: 320 };

function Stops({ stops }: { stops: typeof BRAND_WHITE_STOPS }) {
  return (
    <>
      {stops.map(([o, c]) => (
        <stop key={o} offset={o} stopColor={c} />
      ))}
    </>
  );
}

export function Logo({
  size = "md",
  variant = "compact",
  className = "",
}: {
  size?: Size;
  variant?: Variant;
  className?: string;
}) {
  const id = useId().replace(/:/g, "");
  const full = variant === "full";
  const w = full ? FULL_W[size] : Math.round(COMPACT_H[size] * G.compactAspect);
  const h = full ? Math.round(FULL_W[size] / G.fullAspect) : COMPACT_H[size];
  return (
    <svg
      role="img"
      aria-label={full ? "ChiSetup — Gaming Gear & Setup" : "ChiSetup"}
      viewBox={full ? G.fullViewBox : G.compactViewBox}
      width={w}
      height={h}
      className={`block shrink-0 select-none ${className}`}
    >
      <defs>
        <linearGradient id={`${id}w`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.whiteGradient.y1} y2={G.whiteGradient.y2}>
          <Stops stops={BRAND_WHITE_STOPS} />
        </linearGradient>
        <linearGradient id={`${id}o`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.orangeGradient.y1} y2={G.orangeGradient.y2}>
          <Stops stops={BRAND_ORANGE_STOPS} />
        </linearGradient>
      </defs>
      <path fill={`url(#${id}w)`} d={G.white} />
      <path fill={`url(#${id}o)`} fillRule="evenodd" d={G.orange} />
      {full && (
        <>
          <path fill={G.taglineColor} d={G.tagline} />
          <path fill="#FFFFFF" d={G.bracketsWhite} />
          <path fill="#FF6600" d={G.bracketsOrange} />
        </>
      )}
    </svg>
  );
}
