/**
 * Catalog v2 contract: category tree, brands, typed characteristics and the filter engine
 * shared by the Mini App and the website — see docs/CATALOG-SPECS.md.
 *
 * The backend stores and validates; filtering and facet counting live here, once, so the two
 * storefronts can never disagree about what "PAW3950 · до 55 г" matches. The catalog is small
 * (hundreds of products), so every storefront filters in memory over a full category list.
 */

// ---- schema ---------------------------------------------------------------------

export type SpecType = "number" | "enum" | "multi" | "bool" | "text";
export type ProductCondition = "NEW" | "MARKDOWN" | "USED";
export type CardStatus = "DRAFT" | "AI_FILLED" | "READY";

/** Reserved slug of the virtual "Уценка" collection (products with condition != NEW). */
export const MARKDOWN_COLLECTION_SLUG = "utsenka";

export interface SpecOption {
  /** Stable slug stored in product specs and used in filter URLs. */
  value: string;
  /** Label in the requested language. */
  label: string;
  sort: number;
}

export interface FacetBucket {
  /** Stable id used in URLs, e.g. "45-54" / "lt45" — generated by the backend from min/max. */
  id: string;
  label: string;
  /** Inclusive; null = open. */
  min: number | null;
  max: number | null;
}

export interface SpecAttribute {
  id: string;
  key: string;
  label: string;
  type: SpecType;
  /** Unit in the requested language ("г", "Hz"); null for none. */
  unit?: string | null;
  /** number only: value is stored as {min,max} (DPI 50–30 000). */
  range?: boolean;
  group: string;
  filterable: boolean;
  comparable: boolean;
  required: boolean;
  /** Shown in the one-line summary on product cards (max 3 per category). */
  highlight: boolean;
  sort: number;
  /** Category that defines it (parent attributes are inherited); null = global (all categories). */
  categoryId: string | null;
  options?: SpecOption[];
  /** number + filterable: buckets; absent = min/max range inputs. */
  buckets?: FacetBucket[] | null;
  /** Admin/AI hint how to fill it (ru). Not shown on the storefront. */
  hint?: string | null;
}

export interface SpecGroup {
  key: string;
  label: string;
  sort: number;
}

export interface CatalogCategory {
  id: string;
  slug: string;
  name: string;
  parentId: string | null;
  sortOrder: number;
  showInMenu: boolean;
  /** Mascot/art kind for the site tile (mouse, keyboard, …); null = guessed from the slug. */
  artKind?: string | null;
  /** Active products in this category and all its descendants. */
  productCount: number;
}

export interface CatalogBrand {
  id: string;
  slug: string;
  name: string;
  productCount: number;
}

/**
 * GET /api/catalog/schema (Mini App) and GET /api/public/catalog/schema (site) — localized by
 * Accept-Language / ?lang. Attributes are listed once with their own categoryId; use
 * `attributesFor` to get the inherited list of a category.
 */
export interface CatalogSchema {
  categories: CatalogCategory[];
  brands: CatalogBrand[];
  groups: SpecGroup[];
  attributes: SpecAttribute[];
  /** Labels of the conditions in the requested language. */
  conditions: { value: ProductCondition; label: string }[];
}

// ---- product values ---------------------------------------------------------------

export type SpecValue = number | { min: number; max: number } | string | string[] | boolean;
/** products.specs — attribute key → value (see SpecType). Unknown = key absent. */
export type ProductSpecs = Record<string, SpecValue>;

export interface ProductBrandRef {
  id: string;
  slug: string;
  name: string;
}

/** Catalog fields every product DTO (Mini App, site, admin) carries since V52. */
export interface CatalogFields {
  categoryId?: string | null;
  brandRef?: ProductBrandRef | null;
  condition?: ProductCondition;
  /** Reason of the markdown / state of a used item, in the requested language. */
  conditionNote?: string | null;
  specs?: ProductSpecs;
}

// ---- tree helpers -------------------------------------------------------------------

export function categoryById(schema: Pick<CatalogSchema, "categories">, id: string | null | undefined) {
  return id ? schema.categories.find((c) => c.id === id) ?? null : null;
}

export function categoryBySlug(schema: Pick<CatalogSchema, "categories">, slug: string | null | undefined) {
  return slug ? schema.categories.find((c) => c.slug === slug) ?? null : null;
}

/** Root → … → category. */
export function categoryPath(schema: Pick<CatalogSchema, "categories">, id: string | null | undefined): CatalogCategory[] {
  const out: CatalogCategory[] = [];
  let c = categoryById(schema, id);
  for (let guard = 0; c && guard < 10; guard++) {
    out.unshift(c);
    c = categoryById(schema, c.parentId);
  }
  return out;
}

export function childCategories(schema: Pick<CatalogSchema, "categories">, parentId: string | null): CatalogCategory[] {
  return schema.categories
    .filter((c) => c.parentId === parentId)
    .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name));
}

/** The category and all its descendants. */
export function subtreeIds(schema: Pick<CatalogSchema, "categories">, id: string): Set<string> {
  const ids = new Set<string>([id]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const c of schema.categories) {
      if (c.parentId && ids.has(c.parentId) && !ids.has(c.id)) {
        ids.add(c.id);
        grew = true;
      }
    }
  }
  return ids;
}

/**
 * Attributes that apply to a category: global → root → … → the category itself, by sort.
 * For a parent category (whose products sit in several leaves) only the attributes common to all
 * of them are filterable, which are exactly the ones defined on the parent path.
 */
export function attributesFor(schema: CatalogSchema, categoryId: string | null | undefined): SpecAttribute[] {
  const path = categoryPath(schema, categoryId).map((c) => c.id);
  const rank = new Map<string | null, number>([[null, 0]]);
  path.forEach((id, i) => rank.set(id, i + 1));
  return schema.attributes
    .filter((a) => rank.has(a.categoryId))
    .sort((a, b) => (rank.get(a.categoryId)! - rank.get(b.categoryId)!) || a.sort - b.sort);
}

// ---- formatting --------------------------------------------------------------------------

const nf = (locale: string) => new Intl.NumberFormat(locale === "en" ? "en-US" : locale === "ru" ? "ru-RU" : "uk-UA", { maximumFractionDigits: 3 });

/** "51 г", "50–30 000", "PAW3950", "Да". `yesNo` = [yes, no] in the UI language. */
export function formatSpec(attr: SpecAttribute, value: SpecValue | undefined, locale: string, yesNo: [string, string]): string | null {
  if (value === undefined || value === null) return null;
  const unit = attr.unit ? ` ${attr.unit}` : "";
  const f = nf(locale);
  switch (attr.type) {
    case "number":
      if (typeof value === "number") return f.format(value) + unit;
      if (typeof value === "object" && !Array.isArray(value)) {
        return value.min === value.max ? f.format(value.min) + unit : `${f.format(value.min)}–${f.format(value.max)}${unit}`;
      }
      return null;
    case "enum": {
      const o = attr.options?.find((x) => x.value === value);
      return o ? o.label : null;
    }
    case "multi": {
      if (!Array.isArray(value) || value.length === 0) return null;
      const labels = value.map((v) => attr.options?.find((x) => x.value === v)?.label).filter(Boolean);
      return labels.length ? labels.join(", ") : null;
    }
    case "bool":
      return typeof value === "boolean" ? (value ? yesNo[0] : yesNo[1]) : null;
    case "text":
      return typeof value === "string" && value.trim() ? value.trim() : null;
  }
}

/** Grouped rows for the "Характеристики" block; empty groups are dropped. */
export function specRows(schema: CatalogSchema, categoryId: string | null | undefined, specs: ProductSpecs | undefined, locale: string, yesNo: [string, string]) {
  const attrs = attributesFor(schema, categoryId);
  const groups = [...schema.groups].sort((a, b) => a.sort - b.sort);
  const byGroup = new Map<string, { attr: SpecAttribute; text: string }[]>();
  for (const a of attrs) {
    const text = formatSpec(a, specs?.[a.key], locale, yesNo);
    if (!text) continue;
    if (!byGroup.has(a.group)) byGroup.set(a.group, []);
    byGroup.get(a.group)!.push({ attr: a, text });
  }
  const known = groups.filter((g) => byGroup.has(g.key)).map((g) => ({ group: g, rows: byGroup.get(g.key)! }));
  const orphan = [...byGroup.keys()].filter((k) => !groups.some((g) => g.key === k));
  for (const k of orphan) known.push({ group: { key: k, label: k, sort: 999 }, rows: byGroup.get(k)! });
  return known;
}

/** One-line summary for product cards: "51 г · PAW3950 · 8000 Гц". */
export function specSummary(schema: CatalogSchema, categoryId: string | null | undefined, specs: ProductSpecs | undefined, locale: string, yesNo: [string, string]): string {
  return attributesFor(schema, categoryId)
    .filter((a) => a.highlight)
    .map((a) => (a.type === "bool" ? (specs?.[a.key] === true ? a.label : null) : formatSpec(a, specs?.[a.key], locale, yesNo)))
    .filter(Boolean)
    .slice(0, 3)
    .join(" · ");
}

// ---- filters ---------------------------------------------------------------------------------

/**
 * Filter state. Serialized into URLs as `?brand=a,b&cond=markdown&f.sensor=paw3950,paw3395&f.weight_g=45-54&f.dpi=min..max&price=100..900`.
 * Attribute filters: enum/multi → option values; number with buckets → bucket ids; number without
 * buckets → one "min..max" (either side may be empty); bool → "1".
 */
export interface CatalogFilter {
  /** Category slug (includes the subtree) or MARKDOWN_COLLECTION_SLUG; null = all. */
  category?: string | null;
  brands?: string[];
  conditions?: ProductCondition[];
  priceMin?: number | null;
  priceMax?: number | null;
  inStock?: boolean;
  q?: string;
  attrs?: Record<string, string[]>;
}

export interface FilterableProduct extends CatalogFields {
  id: string;
  title: string;
  priceMinor: number;
  stock?: number;
  /** When present and non-empty, stock is the sum of the variants' (as the backend's effectiveStock). */
  variants?: { stock: number }[];
}

/** Effective stock: sum of the variants when there are any, else the product's own. */
function effectiveStock(p: FilterableProduct): number {
  return p.variants?.length ? p.variants.reduce((n, v) => n + Math.max(0, v.stock), 0) : p.stock ?? 0;
}

export interface FacetValue {
  value: string;
  label: string;
  /** Products that would match if this value were (also) selected, with every other facet applied. */
  count: number;
  selected: boolean;
}

export interface Facet {
  /** "brand" | "cond" | attribute key. */
  key: string;
  label: string;
  kind: "options" | "range" | "bool";
  group?: string;
  unit?: string | null;
  values: FacetValue[];
  /** kind=range: bounds of the current selection without this facet. */
  min?: number;
  max?: number;
  selectedRange?: { min: number | null; max: number | null };
}

function numericOf(v: SpecValue | undefined): { min: number; max: number } | null {
  if (typeof v === "number") return { min: v, max: v };
  if (v && typeof v === "object" && !Array.isArray(v) && typeof (v as { min: number }).min === "number") return v as { min: number; max: number };
  return null;
}

export function parseRange(s: string | undefined): { min: number | null; max: number | null } | null {
  if (!s || !s.includes("..")) return null;
  const [a, b] = s.split("..");
  const min = a.trim() === "" ? null : Number(a);
  const max = b.trim() === "" ? null : Number(b);
  if ((min !== null && !Number.isFinite(min)) || (max !== null && !Number.isFinite(max))) return null;
  return { min, max };
}

function matchesAttr(attr: SpecAttribute, value: SpecValue | undefined, selected: string[]): boolean {
  if (selected.length === 0) return true;
  switch (attr.type) {
    case "enum":
      return typeof value === "string" && selected.includes(value);
    case "multi":
      return Array.isArray(value) && value.some((v) => selected.includes(v));
    case "bool":
      return value === true;
    case "number": {
      const n = numericOf(value);
      if (!n) return false;
      if (attr.buckets?.length) {
        return selected.some((id) => {
          const b = attr.buckets!.find((x) => x.id === id);
          return !!b && (b.min === null || n.max >= b.min) && (b.max === null || n.min <= b.max);
        });
      }
      const r = parseRange(selected[0]);
      if (!r) return true;
      return (r.min === null || n.max >= r.min) && (r.max === null || n.min <= r.max);
    }
    default:
      return true;
  }
}

function normalize(s: string) {
  return s.toLocaleLowerCase().replace(/ё/g, "е").replace(/\s+/g, " ").trim();
}

/** Context resolved once per (schema, filter). */
function resolve(schema: CatalogSchema, filter: CatalogFilter) {
  const cat = filter.category && filter.category !== MARKDOWN_COLLECTION_SLUG ? categoryBySlug(schema, filter.category) : null;
  const scope = cat ? subtreeIds(schema, cat.id) : null;
  const attrs = attributesFor(schema, cat?.id ?? null);
  return { cat, scope, attrs, markdownOnly: filter.category === MARKDOWN_COLLECTION_SLUG };
}

type Ctx = ReturnType<typeof resolve>;

/** Everything except the facet named `skip` ("brand" | "cond" | "price" | attribute key). */
function matches<P extends FilterableProduct>(p: P, f: CatalogFilter, ctx: Ctx, skip?: string): boolean {
  if (ctx.scope && !(p.categoryId && ctx.scope.has(p.categoryId))) return false;
  if (ctx.markdownOnly && (p.condition ?? "NEW") === "NEW") return false;
  if (f.inStock && !(effectiveStock(p) > 0)) return false;
  if (f.q) {
    const q = normalize(f.q);
    const hay = normalize(`${p.title} ${p.brandRef?.name ?? ""}`);
    if (!q.split(" ").every((w) => hay.includes(w))) return false;
  }
  if (skip !== "brand" && f.brands?.length && !(p.brandRef && f.brands.includes(p.brandRef.slug))) return false;
  if (skip !== "cond" && f.conditions?.length && !f.conditions.includes(p.condition ?? "NEW")) return false;
  if (skip !== "price") {
    const uah = p.priceMinor / 100;
    if (f.priceMin != null && uah < f.priceMin) return false;
    if (f.priceMax != null && uah > f.priceMax) return false;
  }
  for (const a of ctx.attrs) {
    if (!a.filterable || a.key === skip) continue;
    const sel = f.attrs?.[a.key];
    if (sel?.length && !matchesAttr(a, p.specs?.[a.key], sel)) return false;
  }
  return true;
}

export function filterProducts<P extends FilterableProduct>(schema: CatalogSchema, products: P[], filter: CatalogFilter): P[] {
  const ctx = resolve(schema, filter);
  return products.filter((p) => matches(p, filter, ctx));
}

/**
 * Facets for the current filter: brand, condition, then the filterable attributes of the selected
 * category (global ones too). A facet's counts ignore its own selection (classic disjunctive
 * faceting), so picking "Attack Shark" still shows how many "ATK" there are. Values with zero
 * products that are not selected are dropped; a facet with < 2 values and no selection is dropped.
 */
export function buildFacets<P extends FilterableProduct>(
  schema: CatalogSchema,
  products: P[],
  filter: CatalogFilter,
  labels: { brand: string; condition: string },
): Facet[] {
  const ctx = resolve(schema, filter);
  const out: Facet[] = [];
  const pool = (skip: string) => products.filter((p) => matches(p, filter, ctx, skip));

  // brand
  {
    const base = pool("brand");
    const counts = new Map<string, number>();
    for (const p of base) if (p.brandRef) counts.set(p.brandRef.slug, (counts.get(p.brandRef.slug) ?? 0) + 1);
    const sel = new Set(filter.brands ?? []);
    const values = schema.brands
      .filter((b) => counts.has(b.slug) || sel.has(b.slug))
      .map((b) => ({ value: b.slug, label: b.name, count: counts.get(b.slug) ?? 0, selected: sel.has(b.slug) }))
      .sort((a, b) => Number(b.selected) - Number(a.selected) || b.count - a.count || a.label.localeCompare(b.label));
    if (values.length > 1 || sel.size) out.push({ key: "brand", label: labels.brand, kind: "options", values });
  }

  // condition (hidden inside the markdown collection itself)
  if (!ctx.markdownOnly) {
    const base = pool("cond");
    const sel = new Set(filter.conditions ?? []);
    const values = schema.conditions
      .map((c) => ({ value: c.value, label: c.label, count: base.filter((p) => (p.condition ?? "NEW") === c.value).length, selected: sel.has(c.value) }))
      .filter((v) => v.count > 0 || v.selected);
    if (values.length > 1 || sel.size) out.push({ key: "cond", label: labels.condition, kind: "options", values });
  }

  for (const a of ctx.attrs) {
    if (!a.filterable || a.type === "text") continue;
    const base = pool(a.key);
    const sel = filter.attrs?.[a.key] ?? [];
    if (a.type === "enum" || a.type === "multi") {
      const values = (a.options ?? [])
        .map((o) => ({
          value: o.value,
          label: o.label,
          count: base.filter((p) => matchesAttr(a, p.specs?.[a.key], [o.value])).length,
          selected: sel.includes(o.value),
        }))
        .filter((v) => v.count > 0 || v.selected);
      if (values.length > 1 || sel.length) out.push({ key: a.key, label: a.label, kind: "options", group: a.group, unit: a.unit, values });
    } else if (a.type === "bool") {
      const count = base.filter((p) => p.specs?.[a.key] === true).length;
      if (count > 0 || sel.length) {
        out.push({ key: a.key, label: a.label, kind: "bool", group: a.group, values: [{ value: "1", label: a.label, count, selected: sel.length > 0 }] });
      }
    } else if (a.type === "number") {
      if (a.buckets?.length) {
        const values = a.buckets
          .map((b) => ({ value: b.id, label: b.label, count: base.filter((p) => matchesAttr(a, p.specs?.[a.key], [b.id])).length, selected: sel.includes(b.id) }))
          .filter((v) => v.count > 0 || v.selected);
        if (values.length > 1 || sel.length) out.push({ key: a.key, label: a.label, kind: "options", group: a.group, unit: a.unit, values });
      } else {
        const nums = base.map((p) => numericOf(p.specs?.[a.key])).filter((x): x is { min: number; max: number } => !!x);
        if (nums.length < 2 && !sel.length) continue;
        const min = Math.min(...nums.map((n) => n.min));
        const max = Math.max(...nums.map((n) => n.max));
        if (min === max && !sel.length) continue;
        out.push({ key: a.key, label: a.label, kind: "range", group: a.group, unit: a.unit, values: [], min, max, selectedRange: parseRange(sel[0]) ?? undefined });
      }
    }
  }
  return out;
}

/** Price bounds (UAH) of the selection ignoring the price filter itself. */
export function priceBounds<P extends FilterableProduct>(schema: CatalogSchema, products: P[], filter: CatalogFilter): { min: number; max: number } | null {
  const ctx = resolve(schema, filter);
  const prices = products.filter((p) => matches(p, filter, ctx, "price")).map((p) => p.priceMinor / 100);
  return prices.length ? { min: Math.floor(Math.min(...prices)), max: Math.ceil(Math.max(...prices)) } : null;
}

/** Number of active filter values (for the "Фильтры (N)" badge); category and q are not counted. */
export function activeFilterCount(f: CatalogFilter): number {
  return (
    (f.brands?.length ?? 0) +
    (f.conditions?.length ?? 0) +
    (f.priceMin != null || f.priceMax != null ? 1 : 0) +
    (f.inStock ? 1 : 0) +
    Object.values(f.attrs ?? {}).reduce((n, v) => n + (v.length ? (v.length === 1 && v[0].includes("..") ? 1 : v.length) : 0), 0)
  );
}

// ---- URL (de)serialization -------------------------------------------------------------------------

const list = (s: string | null | undefined) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);

/** Reads the filter from URLSearchParams (site and Mini App share the format). Category comes from the path on the site. */
export function filterFromParams(sp: URLSearchParams | Record<string, string | string[] | undefined>): CatalogFilter {
  const get = (k: string): string | undefined => {
    if (sp instanceof URLSearchParams) return sp.get(k) ?? undefined;
    const v = sp[k];
    return Array.isArray(v) ? v[0] : v;
  };
  const keys = sp instanceof URLSearchParams ? [...sp.keys()] : Object.keys(sp);
  const attrs: Record<string, string[]> = {};
  for (const k of keys) {
    if (!k.startsWith("f.")) continue;
    const v = get(k);
    if (v) attrs[k.slice(2)] = v.includes("..") ? [v] : list(v);
  }
  const price = parseRange(get("price"));
  const cond = list(get("cond")).map((c) => c.toUpperCase()).filter((c): c is ProductCondition => c === "NEW" || c === "MARKDOWN" || c === "USED");
  return {
    brands: list(get("brand")),
    conditions: cond,
    priceMin: price?.min ?? null,
    priceMax: price?.max ?? null,
    inStock: get("inStock") === "1" || get("inStock") === "true",
    q: get("q") || undefined,
    attrs,
  };
}

/** Writes the filter (without category) into URLSearchParams, stable order. */
export function filterToParams(f: CatalogFilter, base?: URLSearchParams): URLSearchParams {
  const sp = new URLSearchParams(base);
  for (const k of [...sp.keys()]) if (k.startsWith("f.") || ["brand", "cond", "price", "inStock", "q"].includes(k)) sp.delete(k);
  if (f.q) sp.set("q", f.q);
  if (f.brands?.length) sp.set("brand", f.brands.join(","));
  if (f.conditions?.length) sp.set("cond", f.conditions.map((c) => c.toLowerCase()).join(","));
  if (f.priceMin != null || f.priceMax != null) sp.set("price", `${f.priceMin ?? ""}..${f.priceMax ?? ""}`);
  if (f.inStock) sp.set("inStock", "1");
  for (const k of Object.keys(f.attrs ?? {}).sort()) {
    const v = f.attrs![k];
    if (v?.length) sp.set(`f.${k}`, v.join(","));
  }
  return sp;
}

/** Toggles one value of a multi-select facet. */
export function toggleFacet(f: CatalogFilter, key: string, value: string): CatalogFilter {
  const flip = (arr: string[] | undefined) => (arr?.includes(value) ? arr.filter((x) => x !== value) : [...(arr ?? []), value]);
  if (key === "brand") return { ...f, brands: flip(f.brands) };
  if (key === "cond") return { ...f, conditions: flip(f.conditions) as ProductCondition[] };
  return { ...f, attrs: { ...(f.attrs ?? {}), [key]: flip(f.attrs?.[key]) } };
}

/** Keeps brand/price/condition/stock/q, drops attribute filters — used when the category changes. */
export function filterForCategory(f: CatalogFilter, category: string | null): CatalogFilter {
  return { ...f, category, attrs: {} };
}
