CREATE TABLE products (
  id BINARY(16) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  price_minor BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'UAH',
  stock INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_images (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  product_id BINARY(16) NOT NULL,
  url VARCHAR(2048) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_product_images_product
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE orders (
  id BINARY(16) PRIMARY KEY,
  total_minor BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'UAH',
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  address VARCHAR(1024) NOT NULL,
  comment VARCHAR(1024) NULL,
  tg_user_id BIGINT NOT NULL,
  tg_username VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BINARY(16) NOT NULL,
  product_id BINARY(16) NOT NULL,
  title_snapshot VARCHAR(255) NOT NULL,
  price_minor_snapshot BIGINT NOT NULL,
  quantity INT NOT NULL,
  CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE TABLE settings (
  k VARCHAR(128) PRIMARY KEY,
  v VARCHAR(2048) NOT NULL
);
