"use client";

import { useId } from "react";
import { BRAND_ORANGE_STOPS, BRAND_WHITE_STOPS, LOGO_GEOMETRY as G, MARK_GEOMETRY as M } from "@shop/shared";

/**
 * ChiSetup logo for the admin (DESIGN-V3 §6, §8) — the same vector geometry as the Mini App and the
 * site, from `@shop/shared` (generated by docs/brand/v3/tools/gen_brand.py). Paths, not text:
 * crisp at 18–28px and independent of font loading.
 *
 *   - <Wordmark size={22}/>   bare wordmark (sidebar, phone top bar);
 *   - <LogoFull width={280}/> wordmark in HUD brackets + «GAMING GEAR & SETUP» (login, offline);
 *   - <LogoMark size={36}/>   CS monogram tile (collapsed sidebar; same art as app/icon.svg).
 *
 * The ADMIN eyebrow next to the wordmark is markup, not part of the artwork (see Shell).
 */

function Stops({ stops }: { stops: typeof BRAND_WHITE_STOPS }) {
  return (
    <>
      {stops.map(([o, c]) => (
        <stop key={o} offset={o} stopColor={c} />
      ))}
    </>
  );
}

function LogoSvg({ full, width, height, className = "" }: { full: boolean; width: number; height: number; className?: string }) {
  const id = useId().replace(/:/g, "");
  return (
    <svg
      role="img"
      aria-label={full ? "ChiSetup — Gaming Gear & Setup" : "ChiSetup"}
      viewBox={full ? G.fullViewBox : G.compactViewBox}
      width={width}
      height={height}
      className={`block shrink-0 select-none ${className}`}
    >
      <defs>
        <linearGradient id={`${id}w`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.whiteGradient.y1} y2={G.whiteGradient.y2}>
          <Stops stops={BRAND_WHITE_STOPS} />
        </linearGradient>
        <linearGradient id={`${id}o`} gradientUnits="userSpaceOnUse" x1="0" x2="0" y1={G.orangeGradient.y1} y2={G.orangeGradient.y2}>
          <Stops stops={BRAND_ORANGE_STOPS} />
        </linearGradient>
      </defs>
      <path fill={`url(#${id}w)`} d={G.white} />
      <path fill={`url(#${id}o)`} fillRule="evenodd" d={G.orange} />
      {full && (
        <>
          <path fill={G.taglineColor} d={G.tagline} />
          <path fill="#FFFFFF" d={G.bracketsWhite} />
          <path fill="#FF6600" d={G.bracketsOrange} />
        </>
      )}
    </svg>
  );
}

/** Bare wordmark; `size` = rendered height in px (cap height ≈ 74% of it). */
export function Wordmark({ size = 22, className = "" }: { size?: number; className?: string }) {
  return <LogoSvg full={false} height={size} width={Math.round(size * G.compactAspect)} className={className} />;
}

/** Wordmark in HUD brackets + tagline; `width` in px. */
export function LogoFull({ width = 280, className = "" }: { width?: number; className?: string }) {
  return <LogoSvg full width={width} height={Math.round(width / G.fullAspect)} className={className} />;
}

/** CS monogram app icon (same art as app/icon.svg and the PWA icons). Decorative. */
export function LogoMark({ size = 36, className = "" }: { size?: number; className?: string }) {
  const id = useId().replace(/:/g, "");
  return (
    <svg aria-hidden viewBox={M.viewBox} width={size} height={size} className={`block shrink-0 ${className}`}>
      <defs>
        <linearGradient id={`${id}bg`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#151515" />
          <stop offset="1" stopColor="#0E0E10" />
        </linearGradient>
        <linearGradient id={`${id}w`} x1="0" y1="0" x2="0" y2="1">
          <Stops stops={BRAND_WHITE_STOPS} />
        </linearGradient>
        <linearGradient id={`${id}o`} x1="0" y1="0" x2="0" y2="1">
          <Stops stops={BRAND_ORANGE_STOPS} />
        </linearGradient>
      </defs>
      <rect width="512" height="512" rx={M.radius} fill={`url(#${id}bg)`} />
      <rect x="2" y="2" width="508" height="508" rx={M.radius - 2} fill="none" stroke="rgba(255,255,255,.12)" strokeWidth="4" />
      <path fill="#FFFFFF" d={M.bracketsWhite} />
      <path fill="#FF6600" d={M.bracketsOrange} />
      <path fill={`url(#${id}w)`} d={M.white} />
      <path fill={`url(#${id}o)`} d={M.orange} />
    </svg>
  );
}
